/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testvocacional;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author sweet
 */
public class Resultado extends javax.swing.JFrame {

    /**
     * Creates new form Resultado
     */
    public Resultado() {
        Lector.calcularResultados();
        initComponents();
        JLabel[] labels = {primera, segunda, tercera, cuarta, quinta};
        establecerLabels(labels);
        //logo
        ImageIcon icono = new ImageIcon("src/resource/logo.png");
        this.setIconImage(icono.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primerboton = new javax.swing.JButton();
        segundoboton = new javax.swing.JButton();
        tercerboton = new javax.swing.JButton();
        cuartoboton = new javax.swing.JButton();
        quintoboton = new javax.swing.JButton();
        primera = new javax.swing.JLabel();
        segunda = new javax.swing.JLabel();
        tercera = new javax.swing.JLabel();
        cuarta = new javax.swing.JLabel();
        quinta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        textores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(215, 227, 255));
        setResizable(false);

        primerboton.setText("Profesiones del area");
        primerboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primerbotonActionPerformed(evt);
            }
        });

        segundoboton.setText("Profesiones del area");
        segundoboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundobotonActionPerformed(evt);
            }
        });

        tercerboton.setText("Profesiones del area");
        tercerboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tercerbotonActionPerformed(evt);
            }
        });

        cuartoboton.setText("Profesiones del area");
        cuartoboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuartobotonActionPerformed(evt);
            }
        });

        quintoboton.setText("Profesiones del area");
        quintoboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quintobotonActionPerformed(evt);
            }
        });

        primera.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        primera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        segunda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        segunda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tercera.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tercera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cuarta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cuarta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        quinta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        quinta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        textores.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        textores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textores.setText("LOS RESULTADOS DE SU TEST SON ...");
        jPanel1.add(textores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuarta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(quinta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuartoboton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quintoboton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tercera, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(segunda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(primera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(primerboton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(segundoboton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tercerboton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(primerboton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(primera, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(segunda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segundoboton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tercerboton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tercera, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cuarta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(quinta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cuartoboton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(quintoboton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(791, 473));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void primerbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primerbotonActionPerformed
        
        int indice = Lector.areasOrdenadas[0] -1;
        String nombreArea = Lector.areasYCarreras[indice][0];
        Lector.areasYCarreras[indice][0] = "";
        String[] arrayCarreras = Lector.areasYCarreras[indice]; 
        new Carreras(arrayCarreras, nombreArea).setVisible(true);

    }//GEN-LAST:event_primerbotonActionPerformed

    private void segundobotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundobotonActionPerformed
        
        int indice = Lector.areasOrdenadas[1] -1;
        String nombreArea = Lector.areasYCarreras[indice][0];
        Lector.areasYCarreras[indice][0] = "";
        String[] arrayCarreras = Lector.areasYCarreras[indice]; 
        new Carreras(arrayCarreras, nombreArea).setVisible(true);

    }//GEN-LAST:event_segundobotonActionPerformed

    private void tercerbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tercerbotonActionPerformed
        
        int indice = Lector.areasOrdenadas[2] -1;
        String nombreArea = Lector.areasYCarreras[indice][0];
        Lector.areasYCarreras[indice][0] = "";
        String[] arrayCarreras = Lector.areasYCarreras[indice]; 
        new Carreras(arrayCarreras, nombreArea).setVisible(true);

    }//GEN-LAST:event_tercerbotonActionPerformed

    private void cuartobotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuartobotonActionPerformed
        
        int indice = Lector.areasOrdenadas[3] -1;
        String nombreArea = Lector.areasYCarreras[indice][0];
        Lector.areasYCarreras[indice][0] = "";
        String[] arrayCarreras = Lector.areasYCarreras[indice]; 
        new Carreras(arrayCarreras, nombreArea).setVisible(true);

    }//GEN-LAST:event_cuartobotonActionPerformed

    private void quintobotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quintobotonActionPerformed
        
        int indice = Lector.areasOrdenadas[4] -1;
        String nombreArea = Lector.areasYCarreras[indice][0];
        Lector.areasYCarreras[indice][0] = "";
        String[] arrayCarreras = Lector.areasYCarreras[indice]; 
        new Carreras(arrayCarreras, nombreArea).setVisible(true);

    }//GEN-LAST:event_quintobotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultado().setVisible(true);
            }
        });
    }

    
    public void establecerLabels(JLabel[] labels){
        //Establecer nombre de las carreras
        int k = 0;
        for (int indice : Lector.areasOrdenadas) {
            labels[k].setText(Lector.areasYCarreras[indice-1][0]);
            k++;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cuarta;
    private javax.swing.JButton cuartoboton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel primera;
    private javax.swing.JButton primerboton;
    private javax.swing.JLabel quinta;
    private javax.swing.JButton quintoboton;
    private javax.swing.JLabel segunda;
    private javax.swing.JButton segundoboton;
    private javax.swing.JLabel tercera;
    private javax.swing.JButton tercerboton;
    private javax.swing.JLabel textores;
    // End of variables declaration//GEN-END:variables
}
